name: NPM Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        run: |
          curl -o setup-node.sh -sSL https://github.com/actions/setup-node/raw/main/.github/scripts/setup-node.sh
          bash setup-node.sh -v 14
          rm setup-node.sh

      - name: Install Dependencies
        run: npm install

      - name: Publish to NPM
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH }}
